###########
# Explainer #
###########

dataset: 'synthderm'
# number of disentangled knobs
k_dim: 1
#lambda_r: 0.0

image_dir: './data/synthderm/images/'
image_label_dict: './output/classifier/synthderm_malignant/explainer_input/list_attr_2_1350.txt' #path where the training data as [image name, label] is saved. Here label is the bin-index. Refer ./test_classifier.py to see how to create this file from the classifier results.
cls_experiment: './output/classifier/synthderm_malignant' #address where classifier checkpoint is saved
log_dir: './output/discoverer/synthderm_experiments' #address where explainer/discoverer checkpoint and summaries will be saved
name: 'synthderm_malignant_Explainer' #name of the folder at the above address

num_channel: 3
num_class: 2
#number of classes in classifier
num_bins: 2
#number of bins the output class probability between [0,1] is discretized into.
target_class: 1
#the class for which explanation has to be generated
input_size: 64
batch_size: 32
epochs: 300

lambda_GAN: 2
lambda_cyc: 100
lambda_cls: 1

discriminate_every_nth: 5
generate_every_nth: 1

save_summary: 20
# Save sample images after every how many iterations.
save_ckpt: 500
# Save checkpoint after every how many iterations.

ckpt_dir_continue: './output/discoverer/synthderm_experiments/synthderm_malignant_Explainer'

evaluation_batch_size: 16
count_to_save: 10000
# number of samples to save while testing

# hyper-parameters for calculating metrics: influential, distinct, realistic
metrics_batch_size: 32
metrics_epochs: 10
metrics_test_ratio: 0.25
metrics_stability_nx: 5
metrics_stability_var: 0.01
classifier_config: './configs/synthderm_experiments/synthderm_malignant_Classifier.yaml'

# hyperparameters for saving results for substitutability metric
calc_substitutability: False

substitutability_attr: 'malignant'
substitutability_classifier_config: './output/discoverer/synthderm_experiments/synthderm_malignant_Explainer/synthderm_malignant_Classifier_substitutability.yaml'