###########
# Classifier #
###########

# this is a classifier trying to predict if an synthetic image inspired by dermatology cases is malignant or benign
dataset: 'synthderm'
image_dir: './data/synthderm/images/'

image_label_dict: './data/synthderm/malignant_binary_classification.txt'
train: './data/synthderm/malignant/train_ids.npy'
test: './data/synthderm/malignant/test_ids.npy'

log_dir: './output/classifier'
name: 'synthderm_malignant'

num_channel: 3
num_class: 1
input_size: 64
batch_size: 32
epochs: 13
ckpt_dir_continue: ''
