###########
# Classifier #
###########

dataset: 'shapes'
image_dir: '' # Not used for shapes
image_label_dict: './data/shapes/biased/redcyan_binary_classification.txt'
train: './data/shapes/biased/train_ids.npy'
test: './data/shapes/biased/test_ids.npy'

log_dir: './output/classifier'
name: 'shapes-biasedredcyan'

num_channel: 3
num_class: 1
input_size: 64
batch_size: 32
epochs: 5
ckpt_dir_continue: ''
