###########
# Classifier #
###########

# this is a classifier trying to predict smile, but confounded with young and blond
dataset: 'CelebA'
image_dir: './data/CelebA/images/'
image_label_dict: './data/CelebA/biased/Smiling_binary_classification.txt'
train: './data/CelebA/biased/train_ids.npy'
test: './data/CelebA/biased/test_ids.npy'

log_dir: './output/classifier'
name: 'CelebA-biased'

num_channel: 3
num_class: 1
input_size: 128
batch_size: 32
epochs: 5
ckpt_dir_continue: ''
