###########
# Classifier #
###########

# this is a classifier trying to predict smile, but confounded with young and blond
dataset: 'CelebA64'
image_dir: './data/CelebA/images/'

image_label_dict: './data/CelebA/biased/Smiling_binary_classification.txt'
train: './data/CelebA/biased/train_ids.npy'
test: './data/CelebA/biased/test_ids.npy'

export_image_label_dict: './data/CelebA/Smiling_binary_classification.txt'
export_train: './data/CelebA/train_ids.npy'
export_test: './data/CelebA/test_ids.npy'

log_dir: './output/classifier'
name: 'CelebA64-biased'

num_channel: 3
num_class: 1
input_size: 64
batch_size: 32
epochs: 5
ckpt_dir_continue: ''
