###########
# Classifier #
###########

# this is a classifier trying to predict if an inflammatory skin photo is malignant or benign
dataset: 'dermatology'
image_dir: './data/dermatology/data_nov3b/'

image_label_dict: './data/dermatology/inflammatory-malignant_binary_classification.txt'
train: './data/dermatology/inflammatory-malignant/train_ids.npy'
test: './data/dermatology/inflammatory-malignant/test_ids.npy'

log_dir: './output/classifier'
name: 'dermatology-inflammatory-malignant'

num_channel: 3
num_class: 1
input_size: 64
batch_size: 32
epochs: 10
ckpt_dir_continue: ''
