###########
# Discoverer #
###########

dataset: 'dermatology'
# number of disentangled knobs
k_dim: 2
lambda_r: 2.0

image_dir: './data/dermatology/data_nov3b/'
image_label_dict: './output/classifier/dermatology-inflammatory-malignant/explainer_input/list_attr_10_5000.txt' #path where the training data as [image name, label] is saved. Here label is the bin-index. Refer ./test_classifier.py to see how to create this file from the classifier results.
cls_experiment: './output/classifier/dermatology-inflammatory-malignant' #address where classifier checkpoint is saved
log_dir: './output/discoverer_2020_05/dermatology-inflammatory_experiments' #address where explainer/discoverer checkpoint and summaries will be saved
name: 'dermatology-inflammatory_Discoverer_multidim' #name of the folder at the above address

num_channel: 3
num_class: 2
#number of classes in classifier
num_bins: 10
#number of bins the output class probability between [0,1] is discretized into.
target_class: 1
#the class for which explanation has to be generated
input_size: 64
batch_size: 32
epochs: 300

lambda_GAN: 1
lambda_cyc: 100
lambda_cls: 1

discriminate_every_nth: 1
generate_every_nth: 5

save_summary: 20
# Save sample images after every how many iterations.
save_ckpt: 500
# Save checkpoint after every how many iterations.

ckpt_dir_continue: './output/discoverer_2020_05/dermatology-inflammatory_experiments/dermatology-inflammatory_Discoverer_multidim'

count_to_save: 10000
# number of samples to save while testing

# hyper-parameters for calculating metrics: influential, distinct, realistic
metrics_batch_size: 32
metrics_epochs: 10
metrics_test_ratio: 0.25
metrics_stability_nx: 5
metrics_stability_var: 0.01
classifier_config: './configs/dermatology_experiments/dermatology_inflammatory-malignant_Classifier.yaml'


# hyperparameters for saving results for substitutability metric
calc_substitutability: False

substitutability_attr: 'inflammatory-malignant'
substitutability_classifier_config: './output/discoverer_2020_05/dermatology-inflammatory_experiments/dermatology-inflammatory_Discoverer_multidim/dermatology_inflammatory-malignant_Classifier_substitutability.yaml'

