###########
# Classifier #
###########

image_label_dict: './output/classifier/CelebA-YSBBB/explainer_input/Smile/list_attr_celeba.txt'
#path where the training data as [image name, label] is saved. Here label is the bin-index. Refer ../notebooks/Process_Classifier_Output.ipynb to see how to create this file from the classifier results.
cls_experiment: './output/classifier/CelebA-YSBBB' #address where classifier checkpoint is saved
log_dir: './output/explainer' #address where explainer checkpoint and summaries will be saved
name: 'CelebA-Smile-YSBBB' #name of the folder at the above address

num_channel: 3
num_class: 5
#number of classes in classifier
num_bins: 10
#number of bins the output class probability between [0,1] is discretized into.
target_class: 1
#the class for which explanation has to be generated
input_size: 128
batch_size: 32
epochs: 300

lambda_GAN: 1
lambda_cyc: 100
lambda_cls: 1

save_summary: 2
# Save sample images after every how many iterations.

ckpt_dir_continue: './output/explainer/CelebA-Smile-YSBBB'

count_to_save: 100
# number of samples to save while testing