###########
# Classifier #
###########

image_dir: './data/celebA/images' #'./data/CelebA/images/'
image_label_dict: './data/CelebA/list_attr_celeba.txt'
train: './data/CelebA/train_ids.npy'
test: './data/CelebA/test_ids.npy'

log_dir: './output/classifier/CelebA'
name: 'DenseNet'

num_channel: 3
input_size: 128
num_classes: 40
batch_size: 32
epochs: 10
ckpt_dir_continue: ''
