###########
# Classifier #
###########

dataset: 'dsprites'
image_dir: './data/dsprites/images/'
image_label_dict: './data/dsprites/fits_binary_classification.txt'
train: './data/dsprites/train_ids.npy'
test: './data/dsprites/test_ids.npy'

log_dir: './output/classifier'
name: 'dsprites-fits'

num_channel: 1
num_class: 1
input_size: 64
batch_size: 32
epochs: 5
ckpt_dir_continue: ''
