###########
# Discoverer #
###########

dataset: 'CelebA'
# number of disentangled knobs
k_dim: 3
lambda_r: 20.0

image_dir: './data/CelebA/images/'
image_label_dict: './output/classifier/CelebA-Smile/explainer_input/list_attr_10_5000.txt' #path where the training data as [image name, label] is saved. Here label is the bin-index. Refer ./test_classifier.py to see how to create this file from the classifier results.
cls_experiment: './output/classifier/CelebA-Smile' #address where classifier checkpoint is saved
log_dir: './output/discoverer/celeba_experiments' #address where explainer/discoverer checkpoint and summaries will be saved
name: 'celeba_smile_Discoverer_multidim' #name of the folder at the above address

num_channel: 3
num_class: 2
#number of classes in classifier
num_bins: 10
#number of bins the output class probability between [0,1] is discretized into.
target_class: 1
#the class for which explanation has to be generated
input_size: 128
batch_size: 32
epochs: 300

lambda_GAN: 1
lambda_cyc: 100
lambda_cls: 1

discriminate_every_nth: 1
generate_every_nth: 5

save_summary: 20
# Save sample images after every how many iterations.

ckpt_dir_continue: './output/discoverer/celeba_experiments/celeba_smile_Discoverer_multidim'

count_to_save: 10000
# number of samples to save while testing

# hyperparameters for calculating metrics: influenctial, distinct, realistic
metrics_batch_size: 32
metrics_epochs: 10
metrics_test_ratio: 0.25
